ATConversionTask/inputFile  /home/ejungwoo/data/texat/run_0824.dat.19-03-23_23h42m36s.38.root
ATConversionTask/mapmm      /home/ejungwoo/data/texat/txtfiles/mapchantomm.txt
ATConversionTask/mapsi      /home/ejungwoo/data/texat/txtfiles/mapchantosi_CRIB.txt
ATConversionTask/mapX6      /home/ejungwoo/data/texat/txtfiles/mapchantoX6_CRIB.txt
ATConversionTask/mapCsI     /home/ejungwoo/data/texat/txtfiles/mapchantoCsI_CRIB.txt
