<config_common config_common.mac

*LKRun/RunName texat 801 conv
*LKRun/DataPath {reco_data_path}

#################################################################################################
RawData/persistency true
Hit/persistency true

#################################################################################################
TTRootConversionTask/inputFileName  {raw_data_path}/run_0801.root
