RawData/persistency true
Hit/persistency true

*LKRun/RunName  texat 824 raw

TTRootConversionTask/inputFileName  e{HOME}/data/texat/run_0824.dat.19-03-23_23h42m36s.38.root # inputFileName
TTRootConversionTask/mapmmFileName  e{HOME}/data/texat/txtfiles/mapchantomm.txt # mapmmFileName
TTRootConversionTask/mapsiFileName  e{HOME}/data/texat/txtfiles/mapchantosi_CRIB.txt # mapsiFileName
TTRootConversionTask/mapX6FileName  e{HOME}/data/texat/txtfiles/mapchantoX6_CRIB.txt # mapX6FileName
TTRootConversionTask/mapCsIFileName e{HOME}/data/texat/txtfiles/mapchantoCsI_CRIB.txt # mapCsIFileName
